name: Print
on: [push, workflow_dispatch]
jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - name: Print to console
        run: echo Hello, Git Actions!
      - name: Print a few lines
        run: |
          echo First Line
          echo Second Line
      - uses: actions/checkout@v3
      - name: my_python
      - uses: actions/setup-python@v3
      - name: Install dependencies
        run: |
          // python -m pip install --upgrade pip
          // pip install flake8
          python 1.py



